<MainScreen>:
    BoxLayout:
        orientation: 'vertical'

        Button:
            text: 'Menu'
            size_hint: (1, 0.2)
            on_press: root.go_to_menu()

        Button:
            text: 'Orders'
            size_hint: (1, 0.2)
            on_press: root.go_to_orders()

        Button:
            text: 'Settings'
            size_hint: (1, 0.2)
            on_press: root.go_to_settings()
