<TestScreen>:
    BoxLayout:
        orientation: 'vertical'
        padding: [20, 20, 20, 20]
        spacing: 10

        Label:
            text: 'Welcome to the Restaurant Management App'
            font_size: '24sp'
            size_hint_y: None
            height: self.texture_size[1]
            color: 0, 0, 0, 1  # Black text color

        Label:
            text: 'This is a test screen'
            font_size: '18sp'
            size_hint_y: None
            height: self.texture_size[1]
            color: 0.5, 0.5, 0.5, 1  # Gray text color

        Button:
            text: 'Go to Home'
            size_hint_y: None
            height: '50dp'
            on_press:
                root.manager.current = 'home'

        Button:
            text: 'Go to Menu'
            size_hint_y: None
            height: '50dp'
            on_press:
                root.manager.current = 'menu'

        Button:
            text: 'Go to Orders'
            size_hint_y: None
            height: '50dp'
            on_press:
                root.manager.current = 'orders'
